import type { IconName } from "@/components/icons/icons";

/** Texts of the development gallery of the icon family (/dev/icons). */
export const ICON_GALLERY_TEXTS = {
  overline: "Galerie de développement",
  title: "Famille d'icônes Ascend",
  intro:
    "Formes pleines et arrondies, encre noire, un seul accent cobalt par icône. Petite variante : survolez ou tabulez sur une icône pour voir son histoire, jouée une fois. Grande variante : dans sa tuile de verre, l'histoire se joue à l'arrivée, puis l'accent respire deux fois et se pose.",
  boardSmall: "Planche — petite variante (32 et 16 px)",
  boardLarge: "Planche — grande variante (tuile de verre, 88 px)",
  agents: "Agents IA et étapes d'un dossier",
  utility: "Signes utilitaires",
  tilesLight: "Tuiles d'étape — surface claire",
  tilesDark: "Tuiles d'étape — surface sombre",
  states: { idle: "Repos", active: "Active", inactive: "Inactive" },
  labels: {
    dashboard: "Tableau de bord",
    contacts: "Contacts",
    leads: "Leads",
    pipeline: "Pipeline",
    deal: "Deal",
    aiAgent: "Agent IA",
    automation: "Automatisation",
    messages: "Messages",
    calendar: "Calendrier",
    tasks: "Tâches",
    reminders: "Rappels",
    email: "Email",
    phone: "Téléphone",
    humanValidation: "Validation humaine",
    simulation: "Simulation",
    analytics: "Analytics",
    growth: "Croissance",
    priority: "Priorité",
    alert: "Alerte",
    search: "Recherche",
    filters: "Filtres",
    settings: "Paramètres",
    integrations: "Intégrations",
    notifications: "Notifications",
    lea: "Léa — acquisition",
    hugo: "Hugo — qualification",
    emma: "Emma — relation",
    louis: "Louis — rendez-vous",
    sarah: "Sarah — suivi",
    prospect: "Prospect",
    appointment: "Lieu du rendez-vous",
    mandate: "Mandat",
  } satisfies Partial<Record<IconName, string>>,
} as const;
