import { readFile } from "node:fs/promises";
import path from "node:path";

import { expect, type Page } from "@playwright/test";

import { APP_TEXTS } from "@/components/texts";

/**
 * Credentials of the fictitious users.
 *
 * They are read at run time from `fixtures/.generated-credentials.json`, which
 * is git-ignored and regenerated by `npm run db:seed`. No password is ever
 * written in a versioned file.
 */

/** Playwright always runs from the project root. */
const CREDENTIALS_PATH = path.join(process.cwd(), "fixtures", ".generated-credentials.json");

export type FixtureUserKey = "directorA" | "agentA" | "userB";

type CredentialsFile = {
  users: { key: string; email: string; password: string; agencyId: string }[];
};

export type FixtureCredentials = { email: string; password: string; agencyId: string };

let cache: CredentialsFile | null = null;

export async function fixtureUser(key: FixtureUserKey): Promise<FixtureCredentials> {
  if (!cache) {
    let raw: string;
    try {
      raw = await readFile(CREDENTIALS_PATH, "utf8");
    } catch {
      throw new Error(
        "E2E tests: fixtures/.generated-credentials.json is missing. Run `npm run db:reset` against the local Supabase stack first.",
      );
    }
    cache = JSON.parse(raw) as CredentialsFile;
  }

  const user = cache.users.find((candidate) => candidate.key === key);
  if (!user) throw new Error(`E2E tests: no fixture user "${key}" in the credentials file.`);
  return { email: user.email, password: user.password, agencyId: user.agencyId };
}

/** Signs a fictitious user in through the real sign-in screen. */
export async function signIn(page: Page, key: FixtureUserKey): Promise<FixtureCredentials> {
  const user = await fixtureUser(key);

  await page.goto("/connexion");
  await page.getByLabel(APP_TEXTS.auth.emailLabel).fill(user.email);
  await page.getByLabel(APP_TEXTS.auth.passwordLabel).fill(user.password);
  await page.getByRole("button", { name: APP_TEXTS.auth.submit }).click();

  // Generous timeout: the Next.js dev server compiles /contacts on first hit.
  await expect(page).toHaveURL(/\/contacts$/, { timeout: 60_000 });
  await expect(page.getByRole("heading", { level: 1, name: APP_TEXTS.contacts.title })).toBeVisible({
    timeout: 60_000,
  });

  return user;
}
